# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-21 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='', max_length=200, verbose_name='\u5305\u6635\u79f0')),
                ('svn_path', models.CharField(default='', max_length=200, verbose_name='svn\u8def\u5f84')),
                ('local_path', models.CharField(default='', max_length=200, verbose_name='\u672c\u5730\u8def\u5f84')),
            ],
            options={
                'verbose_name': '\u5305\u8282\u70b9',
                'verbose_name_plural': '\u5305\u8282\u70b9',
            },
        ),
        migrations.CreateModel(
            name='PackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=20, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6253\u5305\u7c7b\u578b',
                'verbose_name_plural': '\u6253\u5305\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='pack_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.PackType'),
        ),
    ]
