# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='local_path',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u672c\u5730\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='node',
            name='svn_path',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='svn\u8def\u5f84'),
        ),
    ]
